services:
  users_service:
    build:
      context: "."
      dockerfile: ./apps/users/Dockerfile
    ports: [ "12091:12091" ]
  carts_service:
    build:
      context: "."
      dockerfile: ./apps/carts/Dockerfile
    ports: [ "12092:12092" ]
  auth_service:
    build:
      context: "."
      dockerfile: ./apps/auth/Dockerfile
    ports: [ "12093:12093" ]
  brands_service:
    build:
      context: "."
      dockerfile: ./apps/brands/Dockerfile
    ports: [ "12094:12093" ]
  users_database:
    image: postgres
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "users"
  carts_database:
    image: postgres
    ports: [ "5433:5432" ]
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "carts"
  auth_database:
    image: postgres
    ports: [ "5434:5432" ]
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "auth"
  brands_database:
    image: postgres
    ports: [ "5435:5432" ]
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "brands"
